const { app, BrowserWindow } = require('electron');
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
app.disableHardwareAcceleration();
const deadline = setTimeout(() => app.exit(1), 20000);
app.whenReady().then(async () => {
  const root = path.join(__dirname, '../src/renderer');
  const win = new BrowserWindow({ show: false, width: 420, height: 640, webPreferences: { offscreen: true, backgroundThrottling: false } });
  let html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
  html = html.replace(/<script[^>]*>[\s\S]*?<\/script>/g, '').replace(/<meta\s+http-equiv="Content-Security-Policy"[\s\S]*?\/>/, '').replace(/<link[^>]+>/g, '');
  html = html.replace('</head>', `<style>${fs.readFileSync(path.join(root, 'styles.css'))}\n${fs.readFileSync(path.join(root, 'appearance.css'))}</style></head>`);
  await win.loadURL(`data:text/html;charset=utf-8,${encodeURIComponent(html)}`);
  await win.webContents.executeJavaScript(`window.saves=[]; window.widget={setAppearance: async value => { await new Promise(r=>setTimeout(r,30)); if(window.failSave) throw Error('disk'); window.saves.push(value); return value; }}; void 0;`);
  await win.webContents.executeJavaScript(fs.readFileSync(path.join(root, 'appearance.js'), 'utf8'));
  const result = await win.webContents.executeJavaScript(`(async()=>{
    const wait=ms=>new Promise(r=>setTimeout(r,ms));
    const panel=document.querySelector('#settingsPanel'); panel.inert=false; panel.classList.add('open');
    deckAppearance.apply({theme:'aurora',motion:'fluid'});
    document.querySelector('#settings-tab-design').click();
    const moved=['motionEffectsToggle','glowRange','backgroundOpacityRange','opacityRange'].every(id=>document.querySelector('#settings-design').contains(document.getElementById(id)));
    document.querySelector('[data-theme-choice="graphite"]').click();
    document.querySelector('[data-theme-choice="midnight"]').click();
    await wait(120);
    const saved=window.saves.map(s=>s.theme);
    window.failSave=true;
    document.querySelector('[data-theme-choice="aurora"]').click(); await wait(80);
    const rollback=document.body.dataset.design;
    const tab=document.querySelector('#settings-tab-design'); tab.focus();
    tab.dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowLeft',bubbles:true}));
    const keyboard=document.activeElement.id==='settings-tab-general' && document.querySelector('#settings-design').hidden;
    deckAppearance.selectTab(1);
    await wait(350);
    const box=panel.getBoundingClientRect();
    return {moved,saved,rollback,keyboard,contained:box.bottom<=innerHeight,scrollable:panel.scrollHeight>panel.clientHeight,status:document.querySelector('#appearanceStatus').textContent};
  })()`);
  assert.equal(result.moved, true);
  assert.deepEqual(result.saved, ['graphite', 'midnight']);
  assert.equal(result.rollback, 'midnight');
  assert.equal(result.keyboard, true);
  assert.equal(result.contained, true);
  assert.match(result.status, /Could not save/);
  console.log(JSON.stringify(result));
  clearTimeout(deadline);
  app.exit(0);
}).catch(error => { console.error(error); app.exit(1); });
