const { app, BrowserWindow } = require('electron');
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
app.disableHardwareAcceleration();
const deadline = setTimeout(() => app.exit(1), 20000);
app.whenReady().then(async () => {
  const root = path.join(__dirname, '../src/renderer');
  const win = new BrowserWindow({ show: false, width: 420, height: 640, webPreferences: { offscreen: true, backgroundThrottling: false } });
  let html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
  html = html.replace(/<script[^>]*>[\s\S]*?<\/script>/g, '').replace(/<meta\s+http-equiv="Content-Security-Policy"[\s\S]*?\/>/, '').replace(/<link[^>]+>/g, '');
  html = html.replace('</head>', `<style>${fs.readFileSync(path.join(root, 'styles.css'))}\n${fs.readFileSync(path.join(root, 'appearance.css'))}</style></head>`);
  await win.loadURL(`data:text/html;charset=utf-8,${encodeURIComponent(html)}`);
  await win.webContents.executeJavaScript(`window.saves=[]; window.widget={setAppearance: async value => { await new Promise(r=>setTimeout(r,30)); if(window.failSave) throw Error('disk'); window.saves.push(value); return value; }}; void 0;`);
  await win.webContents.executeJavaScript(fs.readFileSync(path.join(root, 'appearance.js'), 'utf8'));
  const result = await win.webContents.executeJavaScript(`(async()=>{
    const wait=ms=>new Promise(r=>setTimeout(r,ms));
    const panel=document.querySelector('#settingsPanel'); panel.inert=false; panel.classList.add('open');
    deckAppearance.apply({theme:'aurora',motion:'fluid'});
    document.querySelector('#settings-tab-design').click();
    const moved=['motionEffectsToggle','glowRange','backgroundOpacityRange','opacityRange'].every(id=>document.querySelector('#settings-design').contains(document.getElementById(id)));
    document.querySelector('[data-theme-choice="graphite"]').click();
    document.querySelector('[data-theme-choice="midnight"]').click();
    await wait(120);
    const saved=window.saves.map(s=>s.theme);
    window.failSave=true;
    document.querySelector('[data-theme-choice="aurora"]').click(); await wait(80);
    const rollback=document.body.dataset.design;
    const tab=document.querySelector('#settings-tab-design'); tab.focus();
    tab.dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowLeft',bubbles:true}));
    const keyboard=document.activeElement.id==='settings-tab-general' && document.querySelector('#settings-design').hidden;
    deckAppearance.selectTab(1);
    await wait(350);
    const box=panel.getBoundingClientRect();
    return {moved,saved,rollback,keyboard,contained:box.bottom<=innerHeight,scrollable:panel.scrollHeight>panel.clientHeight,status:document.querySelector('#appearanceStatus').textContent};
  })()`);
  assert.equal(result.moved, true);
  assert.deepEqual(result.saved, ['graphite', 'midnight']);
  assert.equal(result.rollback, 'midnight');
  assert.equal(result.keyboard, true);
  assert.equal(result.contained, true);
  assert.match(result.status, /Could not save/);
  const border = await win.webContents.executeJavaScript(`(async () => {
    const wait = ms => new Promise(resolve => setTimeout(resolve, ms));
    const rim = document.querySelector('#chatForm > .chat-activity-border');
    const windowRim = document.querySelector('.window-activity-border');
    const composer = document.querySelector('#chatForm');
    const bounds = rim.getBoundingClientRect();
    const inputBounds = composer.getBoundingClientRect();
    const inputOnly = rim.parentElement === composer && Math.abs(bounds.width - inputBounds.width) <= 2 && Math.abs(bounds.height - inputBounds.height) <= 2;
    const chat = document.querySelector('#chatPanel');
    document.querySelector('#settingsPanel').classList.remove('open');
    document.body.classList.remove('pre-native-visible');
    const checks = [];
    for (const theme of ['aurora', 'graphite', 'midnight', 'cyberpunk']) {
      document.body.dataset.design = theme;
      for (const phase of ['waiting', 'thinking', 'writing', 'tool', 'background', 'idle', 'done', 'error', 'offline']) {
        document.body.dataset.chatState = phase;
        await wait(270);
        const style = getComputedStyle(rim);
        checks.push({ theme, phase, visible: Number(style.opacity) > .5, animated: style.animationName === 'chat-border-orbit' });
      }
    }
    document.body.dataset.chatState = 'thinking';
    await wait(300);
    const defaultWindowOff = Number(getComputedStyle(windowRim).opacity) < .01;
    window.failSave = false;
    document.querySelector('#windowBorderToggle').click();
    await wait(450);
    const bothOn = Number(getComputedStyle(windowRim).opacity) > .8 && Number(getComputedStyle(rim).opacity) > .8;
    document.querySelector('#inputBorderToggle').click();
    await wait(450);
    const windowOnly = Number(getComputedStyle(windowRim).opacity) > .8 && Number(getComputedStyle(rim).opacity) < .01;
    const savedBorders = window.saves.at(-1).inputBorder === false && window.saves.at(-1).windowBorder === true;
    document.querySelector('#inputBorderToggle').click();
    document.querySelector('#windowBorderToggle').click();
    await wait(450);
    const first = getComputedStyle(rim).getPropertyValue('--chat-border-angle');
    await wait(140);
    const rotates = first !== getComputedStyle(rim).getPropertyValue('--chat-border-angle');
    chat.classList.remove('active'); await wait(450);
    const agentsHidden = Number(getComputedStyle(rim).opacity) < .01;
    chat.classList.add('active'); document.body.classList.add('motion-off'); await wait(40);
    const motionOff = getComputedStyle(rim).animationName === 'none';
    document.body.classList.remove('motion-off'); document.body.dataset.design = 'graphite';
    await wait(300);
    return { checks, rotates, agentsHidden, motionOff, inputOnly, defaultWindowOff, bothOn, windowOnly, savedBorders, pointer: getComputedStyle(rim).pointerEvents, mask: getComputedStyle(rim).maskComposite };
  })()`);
  for (const check of border.checks) {
    const active = ['waiting', 'thinking', 'writing', 'tool', 'background'].includes(check.phase);
    assert.equal(check.visible, active, JSON.stringify(check));
    assert.equal(check.animated, active, JSON.stringify(check));
  }
  assert.equal(border.rotates, true);
  assert.equal(border.inputOnly, true);
  for (const key of ['defaultWindowOff', 'bothOn', 'windowOnly', 'savedBorders']) assert.equal(border[key], true, key);
  assert.equal(border.agentsHidden, true);
  assert.equal(border.motionOff, true);
  assert.equal(border.pointer, 'none');
  assert.ok(border.mask.split(',').every(value => value.trim() === 'exclude'));
  fs.mkdirSync(path.join(__dirname, '../tmp'), { recursive: true });
  fs.writeFileSync(path.join(__dirname, '../tmp/activity-border.png'), (await win.webContents.capturePage()).toPNG());
  console.log('PASS activity border: 36 theme/state combinations, rotation, stop, Agents visibility and motion preference');
  console.log(JSON.stringify(result));
  clearTimeout(deadline);
  app.exit(0);
}).catch(error => { console.error(error); app.exit(1); });
