const { contextBridge, ipcRenderer, webUtils } = require("electron");

contextBridge.exposeInMainWorld("widget", {
  dashboard: () => ipcRenderer.invoke("dashboard"),
  history: (sessionId) => ipcRenderer.invoke("history", sessionId),
  models: (sessionId) => ipcRenderer.invoke("models", sessionId),
  commands: (sessionId) => ipcRenderer.invoke("commands", sessionId),
  executeCommand: (payload) => ipcRenderer.invoke("execute-command", payload),
  workspaces: () => ipcRenderer.invoke("workspaces"),
  pickWorkspace: () => ipcRenderer.invoke("pick-workspace"),
  pickFiles: () => ipcRenderer.invoke("pick-files"),
  prepareFiles: (filePaths) => ipcRenderer.invoke("prepare-files", filePaths),
  pathForFile: (file) => webUtils.getPathForFile(file),
  createSession: (options) => ipcRenderer.invoke("create-session", options),
  selectModel: (payload) => ipcRenderer.invoke("select-model", payload),
  send: (payload) => ipcRenderer.invoke("send", payload),
  cancel: (sessionId) => ipcRenderer.invoke("cancel", sessionId),
  openHarness: () => ipcRenderer.invoke("open-harness"),
  openHarnessSession: (sessionId) => ipcRenderer.invoke("open-harness-session", sessionId),
  openProject: () => ipcRenderer.invoke("open-project"),
  openExternal: (url) => ipcRenderer.invoke("open-external", url),
  startHarness: () => ipcRenderer.invoke("start-harness"),
  setAlwaysOnTop: (enabled) => ipcRenderer.invoke("set-always-on-top", enabled),
  setOpacity: (value) => ipcRenderer.invoke("set-opacity", value),
  setSize: (preset) => ipcRenderer.invoke("set-size", preset),
  setAutoStart: (enabled) => ipcRenderer.invoke("set-auto-start", enabled),
  getPreferences: () => ipcRenderer.invoke("get-preferences"),
  getAppInfo: () => ipcRenderer.invoke("app-info"),
  setWindowMode: (mode) => ipcRenderer.invoke("set-window-mode", mode),
  setCompactStatus: (value) => ipcRenderer.invoke("set-compact-status", value),
  windowBounds: () => ipcRenderer.invoke("window-bounds"),
  moveCompactWindow: (value) => ipcRenderer.invoke("move-compact-window", value),
  snapCompactWindow: () => ipcRenderer.invoke("snap-compact-window"),
  beginCompactDrag: (value) => ipcRenderer.send("begin-compact-drag", value),
  moveCompactDrag: (value) => ipcRenderer.send("move-compact-drag", value),
  endCompactDrag: () => ipcRenderer.invoke("end-compact-drag"),
  beginFullDrag: (value) => ipcRenderer.send("begin-full-drag", value),
  moveFullDrag: (value) => ipcRenderer.send("move-full-drag", value),
  endFullDrag: () => ipcRenderer.invoke("end-full-drag"),
  onWindowMode: (listener) => ipcRenderer.on("window-mode", (_event, mode) => listener(mode)),
  onCompactSide: (listener) => ipcRenderer.on("compact-side", (_event, side) => listener(side)),
  onEdgeBounce: (listener) => ipcRenderer.on("edge-bounce", () => listener()),
  notifyAgentComplete: () => ipcRenderer.send("agent-complete"),
});
