const { contextBridge, ipcRenderer, webUtils } = require("electron");

contextBridge.exposeInMainWorld("widget", {
  dashboard: () => ipcRenderer.invoke("dashboard"),
  history: (sessionId) => ipcRenderer.invoke("history", sessionId),
  models: (sessionId) => ipcRenderer.invoke("models", sessionId),
  commands: (sessionId) => ipcRenderer.invoke("commands", sessionId),
  executeCommand: (payload) => ipcRenderer.invoke("execute-command", payload),
  workspaces: () => ipcRenderer.invoke("workspaces"),
  pickWorkspace: () => ipcRenderer.invoke("pick-workspace"),
  pickFiles: () => ipcRenderer.invoke("pick-files"),
  prepareFiles: (fileHandles) => ipcRenderer.invoke("prepare-files", fileHandles),
  captureScreenshot: (kind) => ipcRenderer.invoke("capture-screenshot", kind),
  // Kept under the existing renderer-facing name to avoid a UI migration. webUtils is
  // evaluated inside the isolated preload and the page receives only an opaque handle.
  pathForFile: (file) => {
    let filePath = "";
    try { filePath = webUtils.getPathForFile(file); } catch {}
    return filePath ? ipcRenderer.sendSync("register-selected-file", filePath) : "";
  },
  createSession: (options) => ipcRenderer.invoke("create-session", options),
  selectModel: (payload) => ipcRenderer.invoke("select-model", payload),
  send: (payload) => ipcRenderer.invoke("send", payload),
  cancel: (sessionId) => ipcRenderer.invoke("cancel", sessionId),
  getQueue: (sessionId) => ipcRenderer.invoke("get-queue", sessionId),
  updateQueue: (payload) => ipcRenderer.invoke("update-queue", payload),
  openHarness: () => ipcRenderer.invoke("open-harness"),
  openHarnessSession: (sessionId) => ipcRenderer.invoke("open-harness-session", sessionId),
  openProject: () => ipcRenderer.invoke("open-project"),
  openExternal: (url) => ipcRenderer.invoke("open-external", url),
  startHarness: () => ipcRenderer.invoke("start-harness"),
  setWindowLayer: (value) => ipcRenderer.invoke("set-window-layer", value),
  setOpacity: (value) => ipcRenderer.invoke("set-opacity", value),
  setGlowIntensity: (value) => ipcRenderer.invoke("set-glow-intensity", value),
  setShowThinking: (value) => ipcRenderer.invoke("set-show-thinking", Boolean(value)),
  setCompactAutoExpand: (value) => ipcRenderer.invoke("set-compact-auto-expand", Boolean(value)),
  setSize: (preset) => ipcRenderer.invoke("set-size", preset),
  setAutoStart: (enabled) => ipcRenderer.invoke("set-auto-start", enabled),
  setHotkeys: (bindings) => ipcRenderer.invoke("set-hotkeys", bindings),
  resetHotkeys: () => ipcRenderer.invoke("reset-hotkeys"),
  getPreferences: () => ipcRenderer.invoke("get-preferences"),
  getAppInfo: () => ipcRenderer.invoke("app-info"),
  getUpdateState: () => ipcRenderer.invoke("get-update-state"),
  checkForUpdates: () => ipcRenderer.invoke("check-for-updates"),
  installUpdate: () => ipcRenderer.invoke("install-update"),
  setWindowMode: (mode) => ipcRenderer.invoke("set-window-mode", mode),
  setCompactStatus: (value) => ipcRenderer.invoke("set-compact-status", value),
  beginCompactDrag: (value) => ipcRenderer.send("begin-compact-drag", value),
  moveCompactDrag: (value) => ipcRenderer.send("move-compact-drag", value),
  endCompactDrag: () => ipcRenderer.invoke("end-compact-drag"),
  setEdgePointerActive: (active) => ipcRenderer.send("set-edge-pointer-active", Boolean(active)),
  setCompactHitAreas: (areas) => ipcRenderer.send("set-compact-hit-areas", areas),
  beginFullDrag: (value) => ipcRenderer.send("begin-full-drag", value),
  moveFullDrag: (value) => ipcRenderer.send("move-full-drag", value),
  endFullDrag: () => ipcRenderer.invoke("end-full-drag"),
  onWindowMode: (listener) => ipcRenderer.on("window-mode", (_event, mode) => listener(mode)),
  onFirstVisible: (listener) => ipcRenderer.on("first-visible-entry", () => listener()),
  onCompactSide: (listener) => ipcRenderer.on("compact-side", (_event, side) => listener(side)),
  onEdgeBounce: (listener) => ipcRenderer.on("edge-bounce", () => listener()),
  onQueueUpdate: (listener) => ipcRenderer.on("queue-update", (_event, value) => listener(value)),
  onLiveEvent: (listener) => ipcRenderer.on("live-event", (_event, value) => listener(value)),
  onHotkeyAction: (listener) => ipcRenderer.on("hotkey-action", (_event, value) => listener(value)),
  onHotkeyError: (listener) => ipcRenderer.on("hotkey-error", (_event, value) => listener(value)),
  onScreenshotCaptured: (listener) => ipcRenderer.on("screenshot-captured", (_event, value) => listener(value)),
  onUpdateState: (listener) => ipcRenderer.on("update-state", (_event, value) => listener(value)),
  notifyAgentComplete: () => ipcRenderer.send("agent-complete"),
  selectGameBarSession: (sessionId) => ipcRenderer.send("gamebar-selected-session", sessionId),
  onGameBarSelectSession: (listener) => ipcRenderer.on("gamebar-select-session", (_event, sessionId) => listener(sessionId)),
});
