const { contextBridge, ipcRenderer, webUtils } = require("electron");

contextBridge.exposeInMainWorld("widget", {
  dashboard: () => ipcRenderer.invoke("dashboard"),
  history: (sessionId) => ipcRenderer.invoke("history", sessionId),
  models: (sessionId) => ipcRenderer.invoke("models", sessionId),
  commands: (sessionId) => ipcRenderer.invoke("commands", sessionId),
  executeCommand: (payload) => ipcRenderer.invoke("execute-command", payload),
  workspaces: () => ipcRenderer.invoke("workspaces"),
  pickWorkspace: () => ipcRenderer.invoke("pick-workspace"),
  pickFiles: () => ipcRenderer.invoke("pick-files"),
  prepareFiles: (filePaths) => ipcRenderer.invoke("prepare-files", filePaths),
  pathForFile: (file) => webUtils.getPathForFile(file),
  createSession: (options) => ipcRenderer.invoke("create-session", options),
  selectModel: (payload) => ipcRenderer.invoke("select-model", payload),
  send: (payload) => ipcRenderer.invoke("send", payload),
  cancel: (sessionId) => ipcRenderer.invoke("cancel", sessionId),
  openHarness: () => ipcRenderer.invoke("open-harness"),
  startHarness: () => ipcRenderer.invoke("start-harness"),
  setAlwaysOnTop: (enabled) => ipcRenderer.invoke("set-always-on-top", enabled),
  setOpacity: (value) => ipcRenderer.invoke("set-opacity", value),
  setSize: (preset) => ipcRenderer.invoke("set-size", preset),
  setAutoStart: (enabled) => ipcRenderer.invoke("set-auto-start", enabled),
  getPreferences: () => ipcRenderer.invoke("get-preferences"),
  setWindowMode: (mode) => ipcRenderer.invoke("set-window-mode", mode),
  onWindowMode: (listener) => ipcRenderer.on("window-mode", (_event, mode) => listener(mode)),
  onEdgeBounce: (listener) => ipcRenderer.on("edge-bounce", () => listener()),
  notifyAgentComplete: () => ipcRenderer.send("agent-complete"),
});
